OPENAI_API_KEY = ""
K_WORD_EDU = ["universitat", "carrera", "estudis", "beca", "orientació", "educació", "curs", "aprenentatge",
              "examen", "assignatura", "grau", "màster", "doctorat", "tesi", "recerca", "projecte", "professor",
              "docent", "tutor", "calendari acadèmic", "horari", "programa", "crèdits", "matrícula",
              "avaluació", "pràctiques", "laboratori", "camp de treball", "conselleria", "guia", "suport",
              "orientació professional", "sortides professionals", "mentoria", "coaching",
              "desenvolupament personal", "biblioteca", "recursos en línia", "e-learning", "cursos en línia",
              "MOOC", "webinar", "materials didàctics", "llibres", "publicacions", "ajudes", "subvencions",
              "finançament", "préstecs estudiantils", "ajudes al estudi", "borsa de treball",
              "ocupació estudiantil", "campus", "residència", "allotjament", "activitats extracurriculars",
              "clubs", "esports", "serveis estudiantils", "benestar", "salut mental", "intercanvi",
              "programa Erasmus", "estudi a l'estranger", "alumnes internacionals", "visat estudiantil",
              "mobilitat", "admissió", "inscripció", "requisits", "selectivitat", "proves d'accés",
              "notes de tall", "certificacions", "acreditacions", "titulacions", "innovació educativa",
              "tecnologia educativa", "aprenentatge virtual", "realitat augmentada", "herramientas digitales",
              "software educatiu", "plataformes en línia", "estudiar", "treballar", "evaluació continuada",
              "examen final", "treball de final de grau", "convalidació", "reconocimiento de créditos",
              "transferència de crèdits", "tutoria", "asesoramiento académico", "planificación de carrera",
              "normativa acadèmica", "reglament estudiantil", "política educativa", "formació professional",
              "habilitats professionals", "desenvolupament de carrera", "creixement personal",
              "autoaprenentatge", "autoevaluació", "lideratge", "habilitats comunicatives", "treball en equip",
              "metodologies actives", "aprenentatge basat en projectes", "aprenentatge col·laboratiu",
              "educació inclusiva", "diversitat en l'educació", "necessitats educatives especials", "pedagogia",
              "didàctica", "curriculum", "educació intercultural", "multiculturalitat",
              "igualtat d'oportunitats", "inclusió social", "accessibilitat", "discriminació",
              "ética educativa", "ciutadania", "participació social", "aprenentatge mòbil", "apps educatives",
              "gamificació", "realitat virtual en educació", "simulacions educatives",
              "recursos educatius oberts", "OER", "MOOCs avançats", "projectes de recerca",
              "publicacions científiques", "conferències acadèmiques", "innovació pedagògica", "estudis de cas",
              "metodologies de recerca", "becas de investigación", "grants", "fons de recerca", "ciències",
              "humanitats", "arts", "enginyeria", "tecnologia", "matemàtiques", "ciències de la salut",
              "ciències socials", "educació física", "política de privacitat", "drets dels estudiants",
              "regulacions", "gestió educativa", "administració escolar", "planificació institucional",
              "acreditació acadèmica", "certificació", "estàndards de qualitat", "salut mental",
              "suport emocional", "assessorament psicològic", "seguretat en el campus",
              "prevenció de l'assetjament", "serveis de suport", "orientació a nous estudiants",
              "adaptació universitària", "nota", "nota de tall", "català", "castellà", "llengües", "traducció"]
